"""Tests for filtering auto-generated structure projections."""

import pytest

from lean_explore.extract.projection_filter import (
    filter_auto_generated_projections,
    strip_lean_comments,
)
from lean_explore.extract.types import Declaration


def _declaration(name: str, source_text: str) -> Declaration:
    """Build a declaration with placeholder metadata."""
    return Declaration(
        name=name,
        module="Test",
        docstring=None,
        source_text=source_text,
        source_link="https://github.com/example/blob/main/Test.lean#L1-L1",
        dependencies=None,
    )


def _kept_names(declarations: list[Declaration]) -> tuple[list[str], int]:
    """Run the filter and return the kept names and removal count."""
    filtered, removed_count = filter_auto_generated_projections(declarations)
    return [declaration.name for declaration in filtered], removed_count


class TestStripLeanComments:
    """Tests for stripping Lean comments from source text."""

    @pytest.mark.parametrize(
        ("source", "expected"),
        [
            ("def foo := 1 -- comment\ndef bar := 2", "def foo := 1 def bar := 2"),
            ("def foo /- block comment -/ := 1", "def foo := 1"),
            ("def foo /- outer /- inner -/ outer -/ := 1", "def foo := 1"),
            ("/-- Doc comment\n  more -/\ndef foo := 1", "def foo := 1"),
            (
                "/- header -/\ndef foo := 1 -- line\n/- block -/ def bar := 2",
                "def foo := 1 def bar := 2",
            ),
            ("def foo := 1\ndef bar := 2", "def foo := 1 def bar := 2"),
            ("def foo /- unterminated", "def foo"),
            ("", ""),
        ],
    )
    def test_strips_comments(self, source, expected):
        """Test line, block, nested, and doc comments are removed."""
        assert strip_lean_comments(source) == expected


class TestFilterAutoGeneratedProjections:
    """Tests for filtering auto-generated 'to*' projections."""

    def test_filters_projection_with_shared_source(self):
        """Test that 'to*' projections sharing source with parent are filtered."""
        source = "structure Scheme extends LocallyRingedSpace where\n  local_affine"

        kept, removed = _kept_names(
            [
                _declaration("AlgebraicGeometry.Scheme", source),
                _declaration("AlgebraicGeometry.Scheme.toLocallyRingedSpace", source),
            ]
        )

        assert kept == ["AlgebraicGeometry.Scheme"]
        assert removed == 1

    def test_keeps_legitimate_to_definition(self):
        """Test that legitimate 'to*' definitions with unique source are kept."""
        kept, removed = _kept_names(
            [
                _declaration("Scheme", "structure Scheme extends LocallyRingedSpace"),
                _declaration("IsOpenImmersion.toScheme", "def toScheme : Scheme := _"),
            ]
        )

        assert len(kept) == 2
        assert removed == 0

    def test_filters_based_on_stripped_source(self):
        """Test that comment differences are ignored when comparing source."""
        kept, removed = _kept_names(
            [
                _declaration(
                    "MyStruct", "/-- Doc -/\nstructure MyStruct extends Base where"
                ),
                _declaration(
                    "MyStruct.toBase", "structure MyStruct extends Base where"
                ),
            ]
        )

        assert kept == ["MyStruct"]
        assert removed == 1

    @pytest.mark.parametrize("name", ["Foo.bar", "Foo.tostring", "Foo.to"])
    def test_requires_to_uppercase_prefix(self, name):
        """Test only names shaped like 'toX' are treated as projections."""
        kept, removed = _kept_names(
            [_declaration("Foo", "def shared"), _declaration(name, "def shared")]
        )

        assert kept == ["Foo", name]
        assert removed == 0

    def test_all_sharing_projections_are_removed(self):
        """Test every 'to*' sharing source is dropped, parents are kept."""
        kept, removed = _kept_names(
            [
                _declaration("A", "structure A"),
                _declaration("A.toB", "structure A"),
                _declaration("A.toC", "structure A"),
            ]
        )

        assert kept == ["A"]
        assert removed == 2

    def test_empty_list(self):
        """Test filtering empty list returns empty list."""
        assert _kept_names([]) == ([], 0)

    def test_single_declaration(self):
        """Test single declaration is kept even if it's a 'to*' name."""
        assert _kept_names([_declaration("Foo.toBar", "def toBar := 1")]) == (
            ["Foo.toBar"],
            0,
        )
