"""Core search engine for Lean declarations.

SearchEngine runs hybrid retrieval and ranking:

1. Retrieve candidates by BM25 on declaration names and by semantic search on
   informalizations (see ``indexes``).
2. Fuse both rankings, boost widely depended-on declarations, and optionally
   rerank with a cross-encoder (see ``ranking``).
3. Load the winning declarations from the SQLite database.
"""

import logging
from pathlib import Path
from typing import TYPE_CHECKING

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, create_async_engine

from lean_explore.config import Config
from lean_explore.models import Declaration, SearchResult
from lean_explore.search.indexes import SearchIndexes
from lean_explore.search.ranking import (
    DEPENDENCY_BOOST_POOL_SIZE,
    apply_dependency_boost,
    combine_rerank_scores,
    fuse_rankings,
    rerank_document,
)
from lean_explore.search.tokenization import is_autogenerated

if TYPE_CHECKING:
    import faiss

    from lean_explore.util import EmbeddingClient, RerankerClient

logger = logging.getLogger(__name__)

EMBEDDING_MAX_LENGTH = 512
RERANKER_MAX_LENGTH = 256


def _package_name(module: str) -> str:
    """Return the package of a module path, e.g. "Mathlib" for "Mathlib.Data"."""
    return module.split(".")[0] if module else ""


def _filter_by_packages(
    declarations: dict[int, Declaration], packages: list[str]
) -> dict[int, Declaration]:
    """Keep only declarations whose module belongs to one of the packages."""
    allowed = set(packages)
    return {
        cid: declaration
        for cid, declaration in declarations.items()
        if _package_name(declaration.module) in allowed
    }


def _to_search_result(declaration: Declaration) -> SearchResult:
    """Convert a Declaration ORM object to a SearchResult."""
    return SearchResult(
        id=declaration.id,
        name=declaration.name,
        module=declaration.module,
        docstring=declaration.docstring,
        source_text=declaration.source_text,
        source_link=declaration.source_link,
        dependencies=declaration.dependencies,
        informalization=declaration.informalization,
    )


def _top_results(declarations: list[Declaration], limit: int) -> list[SearchResult]:
    """Convert the first ``limit`` non-autogenerated declarations to results."""
    visible = [d for d in declarations if not is_autogenerated(d.name)]
    return [_to_search_result(d) for d in visible[:limit]]


class SearchEngine:
    """Hybrid search over Lean declarations."""

    def __init__(
        self,
        db_url: str | None = None,
        embedding_client: "EmbeddingClient | None" = None,
        embedding_model_name: str = "Qwen/Qwen3-Embedding-0.6B",
        reranker_client: "RerankerClient | None" = None,
        reranker_model_name: str = "Qwen/Qwen3-Reranker-0.6B",
        faiss_index_path: Path | None = None,
        faiss_ids_map_path: Path | None = None,
        use_local_data: bool = False,
        data_directory: Path | None = None,
    ):
        """Initialize the search engine.

        Args:
            db_url: Database URL. Defaults to configured URL.
            embedding_client: Client for generating embeddings. Created lazily if None.
            embedding_model_name: Name of the embedding model to use.
            reranker_client: Client for reranking results. Created lazily if None.
            reranker_model_name: Name of the reranker model to use.
            faiss_index_path: Path to FAISS index. Defaults to config path.
            faiss_ids_map_path: Path to FAISS ID mapping. Defaults to config path.
            use_local_data: If True, use DATA_DIRECTORY paths (for locally
                generated data). If False, use CACHE_DIRECTORY paths (for
                data downloaded via 'lean-explore data fetch').
            data_directory: Directory holding the index files. Overrides the
                directory chosen by ``use_local_data``.

        Raises:
            FileNotFoundError: If any required index file is missing.
        """
        self._embedding_client = embedding_client
        self._embedding_model_name = embedding_model_name
        self._reranker_client = reranker_client
        self._reranker_model_name = reranker_model_name

        if use_local_data:
            default_directory = Config.ACTIVE_DATA_PATH
            default_db_url = Config.EXTRACTION_DATABASE_URL
        else:
            default_directory = Config.ACTIVE_CACHE_PATH
            default_db_url = Config.DATABASE_URL

        self.db_url = db_url or default_db_url
        self.engine: AsyncEngine = create_async_engine(self.db_url)
        self.indexes = SearchIndexes(
            data_directory or default_directory,
            faiss_index_path=faiss_index_path,
            faiss_ids_map_path=faiss_ids_map_path,
        )

    @property
    def embedding_client(self) -> "EmbeddingClient":
        """Lazily create the embedding client to avoid loading torch at import time."""
        if self._embedding_client is None:
            from lean_explore.util import EmbeddingClient

            self._embedding_client = EmbeddingClient(
                model_name=self._embedding_model_name,
                max_length=EMBEDDING_MAX_LENGTH,
            )
        return self._embedding_client

    @property
    def reranker_client(self) -> "RerankerClient":
        """Lazily create the reranker client to avoid loading torch at import time."""
        if self._reranker_client is None:
            from lean_explore.util import RerankerClient

            self._reranker_client = RerankerClient(
                model_name=self._reranker_model_name,
                max_length=RERANKER_MAX_LENGTH,
            )
        return self._reranker_client

    @property
    def faiss_informal_index(self) -> "faiss.Index":
        """Get the informalization FAISS index."""
        return self.indexes.faiss_index

    @property
    def faiss_informal_id_map(self) -> list[int]:
        """Get the informalization FAISS ID mapping."""
        return self.indexes.faiss_id_map

    async def _semantic_candidates(self, query: str, k: int) -> dict[int, float]:
        """Embed the query, then retrieve candidates from the FAISS index."""
        response = await self.embedding_client.embed([query], is_query=True)
        return self.indexes.semantic_candidates(response.embeddings[0], k)

    async def _load_declarations(self, ids: list[int]) -> dict[int, Declaration]:
        """Load declarations by id, keyed by id; missing ids are omitted."""
        async with AsyncSession(self.engine) as session:
            result = await session.execute(
                select(Declaration).where(Declaration.id.in_(ids))
            )
            return {d.id: d for d in result.scalars().all()}

    async def _rerank(
        self, query: str, candidates: list[Declaration], limit: int
    ) -> list[SearchResult]:
        """Rerank candidates with the cross-encoder and supporting signals."""
        logger.info("Reranking top %d candidates", len(candidates))
        response = await self.reranker_client.rerank(
            query, [rerank_document(d) for d in candidates]
        )
        final_scores = combine_rerank_scores(query, candidates, response.scores)
        ranked = sorted(
            zip(candidates, final_scores), key=lambda item: item[1], reverse=True
        )
        return _top_results([declaration for declaration, _ in ranked], limit)

    async def search(
        self,
        query: str,
        limit: int = 50,
        faiss_k: int = 1000,
        bm25_k: int = 1000,
        rerank_top: int | None = 25,
        packages: list[str] | None = None,
    ) -> list[SearchResult]:
        """Search for Lean declarations.

        Args:
            query: Search query string.
            limit: Maximum number of results to return. Defaults to 50.
            faiss_k: Number of candidates from FAISS index. Defaults to 1000.
            bm25_k: Number of candidates from BM25 index. Defaults to 1000.
            rerank_top: If set, apply cross-encoder reranking to top N candidates.
                Set to 0 or None to skip reranking.
            packages: Optional list of package names to filter by. If provided,
                only declarations from these packages will be returned.

        Returns:
            List of SearchResult objects, ranked by combined score.
        """
        if not query.strip():
            return []

        name_scores = self.indexes.name_candidates(query, bm25_k)
        semantic_scores = await self._semantic_candidates(query, faiss_k)
        fused = fuse_rankings(name_scores, semantic_scores)
        logger.info("Total merged candidates: %d", len(fused))
        if not fused:
            return []

        declarations = await self._load_declarations(
            [cid for cid, _ in fused[:DEPENDENCY_BOOST_POOL_SIZE]]
        )
        boosted = apply_dependency_boost(fused, declarations)
        if packages:
            declarations = _filter_by_packages(declarations, packages)
            boosted = [(cid, score) for cid, score in boosted if cid in declarations]
            logger.info("Filtered to %d in %s", len(declarations), packages)

        rerank = bool(rerank_top and rerank_top > 0)
        pool_size = rerank_top if rerank and rerank_top else limit
        candidates = [
            declarations[cid] for cid, _ in boosted[:pool_size] if cid in declarations
        ]

        if rerank:
            return await self._rerank(query, candidates, limit)
        return _top_results(candidates, limit)

    async def get_by_id(self, declaration_id: int) -> SearchResult | None:
        """Retrieve a declaration by ID.

        Args:
            declaration_id: The declaration ID.

        Returns:
            SearchResult if found, None otherwise.
        """
        async with AsyncSession(self.engine) as session:
            declaration = await session.get(Declaration, declaration_id)
            return _to_search_result(declaration) if declaration else None

    async def get_by_name(self, name: str) -> SearchResult | None:
        """Retrieve a declaration by its exact name.

        Args:
            name: The exact declaration name (e.g., "AlgebraicGeometry.Scheme").

        Returns:
            SearchResult if found, None otherwise.
        """
        async with AsyncSession(self.engine) as session:
            result = await session.execute(
                select(Declaration).where(Declaration.name == name)
            )
            declaration = result.scalar_one_or_none()
            return _to_search_result(declaration) if declaration else None
