"""End-to-end tests for SearchEngine on a small real dataset."""

from collections.abc import AsyncIterator
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from lean_explore.config import Config
from lean_explore.search.engine import SearchEngine
from tests.search.conftest import (
    FakeEmbeddingClient,
    FakeRerankerClient,
    SearchData,
)


@pytest.fixture
async def engine(search_data: SearchData) -> AsyncIterator[SearchEngine]:
    """A SearchEngine over the fixture dataset with fake models."""
    search_engine = SearchEngine(
        db_url=search_data.db_url,
        embedding_client=FakeEmbeddingClient(),
        reranker_client=FakeRerankerClient(),
        data_directory=search_data.directory,
    )
    yield search_engine
    await search_engine.engine.dispose()


async def names(engine: SearchEngine, query: str, **options) -> list[str]:
    """Search with a BM25 depth that fits the small dataset; return names."""
    results = await engine.search(query, **{"bm25_k": 20, **options})
    return [result.name for result in results]


class TestRanking:
    """Regression tests pinning rankings on the fixture dataset."""

    async def test_exact_name_query(self, engine: SearchEngine):
        """An exact name ranks first, followed by closely related lemmas."""
        assert (await names(engine, "Nat.add", limit=3)) == [
            "Nat.add",
            "Nat.add_comm",
            "Nat.add_assoc",
        ]

    async def test_natural_language_query(self, engine: SearchEngine):
        """A description of a statement finds it by meaning."""
        assert (await names(engine, "addition commutative", limit=3)) == [
            "Nat.add_comm",
            "Nat.add",
            "Nat.add_assoc",
        ]

    async def test_unreranked_query_keeps_exact_match_first(self, engine: SearchEngine):
        """Without reranking, the exact name match still ranks first.

        Later positions are not pinned: they include score ties whose order
        depends on platform floating point.
        """
        fused_only = await names(engine, "Nat.add", limit=5, rerank_top=0)

        assert fused_only[0] == "Nat.add"
        assert len(fused_only) == 5


class TestSearchOptions:
    """Tests for limit, rerank, and package options."""

    @pytest.mark.parametrize("query", ["", "   "])
    async def test_blank_query(self, engine: SearchEngine, query: str):
        """Blank queries return nothing without touching the indices."""
        assert await engine.search(query) == []
        assert engine._embedding_client.calls == []

    @pytest.mark.parametrize("limit", [1, 3, 7])
    async def test_limit(self, engine: SearchEngine, limit: int):
        """At most ``limit`` results are returned."""
        assert len(await names(engine, "prime", limit=limit)) == limit

    async def test_rerank_top_limits_reranked_pool(self, engine: SearchEngine):
        """Only the top ``rerank_top`` candidates are sent to the cross-encoder."""
        await names(engine, "prime", rerank_top=4)

        _, documents = engine._reranker_client.calls[-1]
        assert len(documents) == 4

    @pytest.mark.parametrize("rerank_top", [0, None])
    async def test_rerank_disabled(self, engine: SearchEngine, rerank_top):
        """A zero or missing rerank_top skips the cross-encoder."""
        await names(engine, "prime", rerank_top=rerank_top)

        assert engine._reranker_client.calls == []

    async def test_autogenerated_declarations_are_hidden(self, engine: SearchEngine):
        """Structure constructors ending in .mk never appear in results."""
        results = await names(engine, "Nat.Prime.mk", limit=30)
        unreranked = await names(engine, "Nat.Prime.mk", limit=30, rerank_top=0)

        assert "Nat.Prime.mk" not in results + unreranked
        assert "Nat.Prime" in results

    @pytest.mark.parametrize(
        ("packages", "prefixes"),
        [(["Mathlib"], ("Mathlib.",)), (["Init", "Std"], ("Init.", "Std."))],
    )
    async def test_package_filter(
        self, engine: SearchEngine, packages: list[str], prefixes: tuple[str, ...]
    ):
        """Only declarations from the requested packages are returned."""
        results = await engine.search(
            "prime number", bm25_k=20, limit=30, packages=packages
        )

        assert results
        assert all(result.module.startswith(prefixes) for result in results)

    async def test_no_candidates(self, engine: SearchEngine):
        """If neither index returns candidates, the result is empty."""
        with (
            patch.object(engine.indexes, "name_candidates", return_value={}),
            patch.object(engine.indexes, "semantic_candidates", return_value={}),
        ):
            assert await engine.search("anything") == []


class TestLookup:
    """Tests for retrieving declarations directly."""

    async def test_get_by_id(self, engine: SearchEngine):
        """Existing ids return the full declaration; unknown ids return None."""
        result = await engine.get_by_id(1)

        assert result is not None
        assert (result.name, result.module) == ("Nat.add", "Init.Prelude")
        assert result.source_link == "https://example.com/Nat.add"
        assert await engine.get_by_id(999) is None

    async def test_get_by_name(self, engine: SearchEngine):
        """Exact names are found; unknown names return None."""
        result = await engine.get_by_name("List.map")

        assert result is not None and result.id == 10
        assert await engine.get_by_name("List.nope") is None


class TestConstruction:
    """Tests for engine configuration and lazy model clients."""

    def test_missing_data_raises(self, tmp_path: Path):
        """A directory without index files is rejected up front."""
        with pytest.raises(FileNotFoundError, match="data fetch"):
            SearchEngine(db_url="sqlite+aiosqlite://", data_directory=tmp_path)

    @pytest.mark.parametrize(
        ("use_local_data", "directory_setting", "url_setting"),
        [
            (False, "ACTIVE_CACHE_PATH", "DATABASE_URL"),
            (True, "ACTIVE_DATA_PATH", "EXTRACTION_DATABASE_URL"),
        ],
    )
    def test_default_locations(
        self,
        search_data: SearchData,
        use_local_data: bool,
        directory_setting: str,
        url_setting: str,
    ):
        """Downloaded data and locally extracted data use different defaults."""
        with (
            patch.object(Config, directory_setting, search_data.directory),
            patch.object(Config, url_setting, search_data.db_url),
        ):
            search_engine = SearchEngine(use_local_data=use_local_data)

        assert search_engine.db_url == search_data.db_url
        assert search_engine.indexes.bm25_raw_path.parent == search_data.directory

    def test_model_clients_are_created_lazily(self, search_data: SearchData):
        """Model clients are built on first use with the configured model names."""
        search_engine = SearchEngine(
            db_url=search_data.db_url,
            data_directory=search_data.directory,
            embedding_model_name="embed-model",
            reranker_model_name="rerank-model",
        )
        with (
            patch("lean_explore.util.EmbeddingClient") as embedding_class,
            patch("lean_explore.util.RerankerClient") as reranker_class,
        ):
            assert search_engine.embedding_client is search_engine.embedding_client
            assert search_engine.reranker_client is search_engine.reranker_client

        embedding_class.assert_called_once_with(
            model_name="embed-model", max_length=512
        )
        reranker_class.assert_called_once_with(
            model_name="rerank-model", max_length=256
        )

    def test_faiss_accessors_delegate_to_indexes(self, engine: SearchEngine):
        """Legacy FAISS accessors expose the loaded index and id map."""
        assert engine.faiss_informal_index is engine.indexes.faiss_index
        assert engine.faiss_informal_id_map == engine.indexes.faiss_id_map

    def test_injected_clients_are_used(self):
        """Explicit clients are returned without constructing new ones."""
        client = MagicMock()
        search_engine = SearchEngine.__new__(SearchEngine)
        search_engine._embedding_client = client
        search_engine._reranker_client = client

        assert search_engine.embedding_client is client
        assert search_engine.reranker_client is client
