"""Tests for tokenization of declaration names and natural language."""

import pytest

from lean_explore.search.tokenization import (
    is_autogenerated,
    tokenize_raw,
    tokenize_spaced,
    tokenize_words,
)


@pytest.mark.parametrize(
    ("text", "tokens"),
    [
        ("Nat.add", ["nat", "add"]),
        ("my_function", ["my", "function"]),
        ("myFunction", ["my", "function"]),
        ("MyStruct", ["my", "struct"]),
        ("List.length_map", ["list", "length", "map"]),
        ("", []),
    ],
)
def test_tokenize_spaced(text: str, tokens: list[str]):
    """Names split on dots, underscores, and camelCase boundaries."""
    assert tokenize_spaced(text) == tokens


@pytest.mark.parametrize(
    ("text", "tokens"),
    [("Nat.add", ["nat.add"]), ("List.map", ["list.map"]), ("", [])],
)
def test_tokenize_raw(text: str, tokens: list[str]):
    """Raw tokenization keeps the whole lowercased name as one token."""
    assert tokenize_raw(text) == tokens


@pytest.mark.parametrize(
    ("text", "tokens"),
    [
        ("A prime, dividing a product!", ["a", "prime", "dividing", "a", "product"]),
        ("Nat.add_comm", ["nat", "add_comm"]),
        ("", []),
    ],
)
def test_tokenize_words(text: str, tokens: list[str]):
    """Natural language splits on whitespace and punctuation."""
    assert tokenize_words(text) == tokens


@pytest.mark.parametrize(
    ("name", "expected"),
    [
        ("Nat.mk", True),
        ("MyStruct.mk", True),
        ("Nat.add", False),
        ("List.length", False),
        ("mk", False),
    ],
)
def test_is_autogenerated(name: str, expected: bool):
    """Only structure constructors ending in .mk count as autogenerated."""
    assert is_autogenerated(name) is expected
